import nodemailer from 'nodemailer';
import dotenv from 'dotenv';
dotenv.config();

const ADMIN_EMAIL = process.env.SMTP_USER || 'sheth.jainam.coder@gmail.com';
const ADMIN_PASS = process.env.SMTP_PASS || 'piavlgmkshthjxkb';

export const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: ADMIN_EMAIL,
    pass: ADMIN_PASS,
  },
});

/**
 * Send welcome email to registered user + admin alert to sheth.jainam.coder@gmail.com
 */
export async function sendRegistrationNotification({
  name,
  email,
  company = 'Growth Partner',
  adSpend = '$50,000 – $150,000 / month',
  role = 'Growth Lead',
}) {
  const timestamp = new Date().toLocaleString('en-US', {
    timeZone: 'Asia/Kolkata',
    dateStyle: 'full',
    timeStyle: 'medium',
  });

  // 1. Welcome Email for the registering user (with Jainam in BCC)
  const userWelcomeHtml = `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0b1326; color: #dae2fd; margin: 0; padding: 20px; }
      .container { max-width: 600px; margin: 0 auto; background: #131b2e; border: 1px solid rgba(255,255,255,0.1); border-radius: 20px; overflow: hidden; box-shadow: 0 20px 40px rgba(0,0,0,0.5); }
      .header { background: linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%); padding: 36px 30px; text-align: center; }
      .logo { font-size: 26px; font-weight: 800; color: #ffffff; letter-spacing: -0.5px; }
      .logo span { color: #60a5fa; }
      .badge { display: inline-block; background: rgba(52, 211, 153, 0.2); border: 1px solid #34d399; color: #34d399; font-size: 11px; font-weight: 700; padding: 4px 12px; rounded: 20px; border-radius: 20px; margin-top: 10px; }
      .body-content { padding: 32px 30px; }
      h2 { color: #ffffff; font-size: 20px; margin-top: 0; }
      p { color: #94a3b8; font-size: 14px; line-height: 1.6; }
      .info-box { background: #0b1326; border-radius: 12px; padding: 18px; border: 1px solid rgba(255,255,255,0.06); margin: 20px 0; }
      .info-row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 13px; border-bottom: 1px solid rgba(255,255,255,0.04); }
      .info-label { color: #64748b; font-weight: 600; }
      .info-val { color: #f8fafc; font-weight: 700; }
      .cta-btn { display: block; width: 100%; box-sizing: border-box; text-align: center; background: linear-gradient(90deg, #6366f1, #8b5cf6); color: #ffffff !important; text-decoration: none; font-weight: 700; font-size: 14px; padding: 14px 20px; border-radius: 12px; margin-top: 24px; box-shadow: 0 10px 25px rgba(99,102,241,0.4); }
      .footer { padding: 20px 30px; background: #0e1526; text-align: center; font-size: 11px; color: #64748b; border-top: 1px solid rgba(255,255,255,0.05); }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="logo">Pulse<span>IQ</span></div>
        <div style="color: #c7d2fe; font-size: 13px; margin-top: 4px;">Marketing Intelligence & Autonomous Telemetry</div>
        <div class="badge">● ACCOUNT ACTIVATED</div>
      </div>
      <div class="body-content">
        <h2>Welcome to PulseIQ, ${name}!</h2>
        <p>Your workspace access for <strong>${company}</strong> has been configured. You can now audit cross-network campaign pacing, view real-time Markov attribution, and prevent ad spend bleed.</p>
        
        <div class="info-box">
          <div style="font-size: 11px; font-weight: 800; color: #818cf8; text-transform: uppercase; margin-bottom: 8px;">Registered Account Credentials</div>
          <div class="info-row"><span class="info-label">Account Name:</span><span class="info-val">${name}</span></div>
          <div class="info-row"><span class="info-label">Work Email:</span><span class="info-val">${email}</span></div>
          <div class="info-row"><span class="info-label">Company:</span><span class="info-val">${company}</span></div>
          <div class="info-row"><span class="info-label">Ad Budget Scope:</span><span class="info-val">${adSpend}</span></div>
          <div class="info-row"><span class="info-label">Admin Notification:</span><span class="info-val">sheth.jainam.coder@gmail.com</span></div>
        </div>

        <a href="http://localhost:3000" class="cta-btn">Open PulseIQ Live Dashboard →</a>
      </div>
      <div class="footer">
        Automated alert generated by PulseIQ AI Gateway • Admin: sheth.jainam.coder@gmail.com<br>
        Timestamp: ${timestamp} (IST)
      </div>
    </div>
  </body>
  </html>
  `;

  // 2. Admin Alert for sheth.jainam.coder@gmail.com
  const adminAlertHtml = `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #f8fafc; padding: 20px; }
      .card { max-width: 580px; margin: auto; background: #1e293b; border-radius: 16px; border: 1px solid #334155; padding: 24px; box-shadow: 0 10px 30px rgba(0,0,0,0.4); }
      h2 { color: #38bdf8; font-size: 18px; margin-top: 0; display: flex; align-items: center; gap: 8px; }
      .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #334155; font-size: 13px; }
      .badge { background: #0284c7; color: white; padding: 2px 8px; border-radius: 4px; font-weight: bold; font-size: 11px; }
    </style>
  </head>
  <body>
    <div class="card">
      <h2>🚨 New User Registered on PulseIQ</h2>
      <p style="color: #94a3b8; font-size: 13px;">A new account has registered on the platform. Notification sent to <strong>${ADMIN_EMAIL}</strong>.</p>
      
      <div class="row"><strong>User Name:</strong> <span>${name}</span></div>
      <div class="row"><strong>User Email:</strong> <span style="color:#38bdf8;">${email}</span></div>
      <div class="row"><strong>Company:</strong> <span>${company}</span></div>
      <div class="row"><strong>Estimated Monthly Ad Spend:</strong> <span>${adSpend}</span></div>
      <div class="row"><strong>Assigned Role:</strong> <span class="badge">${role}</span></div>
      <div class="row"><strong>Registered At:</strong> <span>${timestamp}</span></div>

      <div style="margin-top: 20px; padding: 12px; background: #0f172a; border-radius: 8px; font-size: 12px; color: #a5f3fc;">
        ✓ Welcome email successfully dispatched to <strong>${email}</strong>.<br>
        ✓ All registrations are monitored by <strong>${ADMIN_EMAIL}</strong>.
      </div>
    </div>
  </body>
  </html>
  `;

  const userMailOptions = {
    from: `"PulseIQ Intelligence" <${ADMIN_EMAIL}>`,
    to: email,
    bcc: ADMIN_EMAIL,
    subject: `🎉 Welcome to PulseIQ Marketing Intelligence — Account Activated (${name})`,
    html: userWelcomeHtml,
  };

  const adminMailOptions = {
    from: `"PulseIQ Alerts" <${ADMIN_EMAIL}>`,
    to: ADMIN_EMAIL,
    subject: `🔔 [PulseIQ Alert] New User Registered: ${name} (${email})`,
    html: adminAlertHtml,
  };

  const [userResult, adminResult] = await Promise.all([
    transporter.sendMail(userMailOptions),
    transporter.sendMail(adminMailOptions),
  ]);

  return {
    success: true,
    userMessageId: userResult.messageId,
    adminMessageId: adminResult.messageId,
    notifiedAdmin: ADMIN_EMAIL,
  };
}

/**
 * Send 6-digit password reset OTP email to user and admin sheth.jainam.coder@gmail.com
 */
export async function sendPasswordResetOtp({ email, otp, name = 'PulseIQ User' }) {
  const timestamp = new Date().toLocaleString('en-US', {
    timeZone: 'Asia/Kolkata',
    dateStyle: 'full',
    timeStyle: 'medium',
  });

  const resetHtml = `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0b1326; color: #dae2fd; margin: 0; padding: 20px; }
      .container { max-width: 580px; margin: 0 auto; background: #131b2e; border: 1px solid rgba(255,255,255,0.1); border-radius: 20px; overflow: hidden; box-shadow: 0 20px 40px rgba(0,0,0,0.5); }
      .header { background: linear-gradient(135deg, #4c1d95 0%, #312e81 100%); padding: 32px 28px; text-align: center; }
      .logo { font-size: 26px; font-weight: 800; color: #ffffff; }
      .logo span { color: #60a5fa; }
      .body-content { padding: 32px 28px; }
      h2 { color: #ffffff; font-size: 20px; margin-top: 0; }
      p { color: #94a3b8; font-size: 14px; line-height: 1.6; }
      .otp-box { background: #0b1326; border: 2px dashed #818cf8; border-radius: 16px; padding: 20px; text-align: center; margin: 24px 0; }
      .otp-code { font-family: monospace; font-size: 36px; font-weight: 900; letter-spacing: 8px; color: #38bdf8; text-shadow: 0 0 15px rgba(56,189,248,0.4); }
      .expiry { font-size: 12px; color: #f59e0b; margin-top: 8px; }
      .security-note { font-size: 12px; color: #64748b; background: rgba(255,255,255,0.03); padding: 12px; border-radius: 8px; border-left: 3px solid #6366f1; }
      .footer { padding: 18px 28px; background: #0e1526; text-align: center; font-size: 11px; color: #64748b; border-top: 1px solid rgba(255,255,255,0.05); }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="logo">Pulse<span>IQ</span></div>
        <div style="color: #c7d2fe; font-size: 13px; margin-top: 4px;">Security & Password Recovery</div>
      </div>
      <div class="body-content">
        <h2>Password Reset Verification Code</h2>
        <p>Hello <strong>${name}</strong>,</p>
        <p>A request was received to reset the password for your PulseIQ workspace account (<code>${email}</code>).</p>
        
        <p>Use the 6-digit verification code below to authorize your password change:</p>

        <div class="otp-box">
          <div style="font-size: 11px; font-weight: 700; color: #a5b4fc; text-transform: uppercase; margin-bottom: 6px;">Your One-Time Code (OTP)</div>
          <div class="otp-code">${otp}</div>
          <div class="expiry">⏱ Valid for the next 10 minutes</div>
        </div>

        <div class="security-note">
          If you did not request this password reset, you can safely ignore this email. Your current password remains protected.
        </div>
      </div>
      <div class="footer">
        Dispatched by PulseIQ Security Gateway • Admin: ${ADMIN_EMAIL}<br>
        Timestamp: ${timestamp} (IST)
      </div>
    </div>
  </body>
  </html>
  `;

  const mailOptions = {
    from: `"PulseIQ Security" <${ADMIN_EMAIL}>`,
    to: email,
    bcc: ADMIN_EMAIL,
    subject: `🔐 PulseIQ Password Reset OTP: ${otp}`,
    html: resetHtml,
  };

  const result = await transporter.sendMail(mailOptions);
  return {
    success: true,
    messageId: result.messageId,
    notifiedAdmin: ADMIN_EMAIL,
  };
}
